#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softwareprojekt2015
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IPLookup")]
	public partial class IPLookupLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertIPLookupTable(IPLookupTable instance);
    partial void UpdateIPLookupTable(IPLookupTable instance);
    partial void DeleteIPLookupTable(IPLookupTable instance);
    #endregion
		
		public IPLookupLINQDataContext() : 
				base(global::Softwareprojekt2015.Properties.Settings.Default.IPLookupConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IPLookupLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPLookupLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPLookupLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPLookupLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IPLookupTable> IPLookupTable
		{
			get
			{
				return this.GetTable<IPLookupTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IPLookupTable")]
	public partial class IPLookupTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _startAddress;
		
		private System.Nullable<long> _endAddress;
		
		private string _countryShort;
		
		private string _type;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnstartAddressChanging(System.Nullable<long> value);
    partial void OnstartAddressChanged();
    partial void OnendAddressChanging(System.Nullable<long> value);
    partial void OnendAddressChanged();
    partial void OncountryShortChanging(string value);
    partial void OncountryShortChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public IPLookupTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startAddress", DbType="BigInt")]
		public System.Nullable<long> startAddress
		{
			get
			{
				return this._startAddress;
			}
			set
			{
				if ((this._startAddress != value))
				{
					this.OnstartAddressChanging(value);
					this.SendPropertyChanging();
					this._startAddress = value;
					this.SendPropertyChanged("startAddress");
					this.OnstartAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endAddress", DbType="BigInt")]
		public System.Nullable<long> endAddress
		{
			get
			{
				return this._endAddress;
			}
			set
			{
				if ((this._endAddress != value))
				{
					this.OnendAddressChanging(value);
					this.SendPropertyChanging();
					this._endAddress = value;
					this.SendPropertyChanged("endAddress");
					this.OnendAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countryShort", DbType="NChar(2)")]
		public string countryShort
		{
			get
			{
				return this._countryShort;
			}
			set
			{
				if ((this._countryShort != value))
				{
					this.OncountryShortChanging(value);
					this.SendPropertyChanging();
					this._countryShort = value;
					this.SendPropertyChanged("countryShort");
					this.OncountryShortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NChar(4)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
